### ISSUE TITLE
Launch Checklist

### ISSUE THREAD

**Issue by lynnandtonic** [lynnandtonic/oss-valentines#8]
For organizational purposes (and my brain), I’m making a quick list of features + rando things for launch

- [x] Log in / Log out with GitHub
- [x] App adds your GitHub avatar/username to FROM: area
- [x] Search for a GitHub recipient to send the valentine to
- [x] App adds recipient GitHub avatar/username to TO: area
- [x] Remove recipient and find a different one
- [x] Ship valentine to receive unique URL
- [x] Copy URL to clipboard 
- [x] Tweet (app constructs a tweet for them)
- [x] Change the instructions `<h2>` text depending on view
- [x] default OG image
- [x] Custom OG image for recipient view
- [x] Correct meta titles/desc/etc + OG images for all views
- [x] Good alt descriptions for valentines
- [x] Browser + responsive testing
- [x] Downloadable valentines + goodies
- [x] Domain + DNS
- [x] Create oAuth tokens for app on Netlify GitHub account with prod domain
- [x] UTM links for footer (Drew to provide)
- [x] Add Google Tags snippet (Drew put in Slack)
- [x] Snazzy favicon?
- [x] ~What if someone’s GitHub username is really long? 39 characters is the max~ (not gonna worry about it right now)
- [x] The sender and recipient names don't currently scale as the viewport is resized
- [x] Gracefully handle fruitless github searches
  - [x] Lynn to make error state
  - [x] Wire it up
- [x] UI feedback for copy URL 
  - [x] Lynn to make error state
  - [x] Wire it up
- [x] Should recipient and sender avatars/handles link to their github profiles?
- [x] Is the Twitter handle in the generated tweet their GitHub handle? (they might be different?)
- [x] After you login, take you back to the card you selected (maybe, Phil to look into)
  - [x] ~If this can’t happen, reorder steps in the introductory copy on homepage so 1. is Log in with GitHub~
- [x] For logged out people, change "Log in with GitHub" button on Recipient view to "Create your own" and link to homepage
- [x] Donate (on share view + recipient view, with different language) 
- [x] Include organizations as recipients
- [x] Tracking
- [x] 404 page
